indexdomconnect = {name: "indexdomconnect"}

############################################################
indexdomconnect.initialize = () ->
    global.postprocessimageBackground = document.getElementById("postprocessimage-background")
    global.postprocessimageResultSvg = document.getElementById("postprocessimage-result-svg")
    global.postprocesssettingsControl = document.getElementById("postprocesssettings-control")
    global.minimalVolumeInput = document.getElementById("minimal-volume-input")
    global.minimalVolumeRangeInput = document.getElementById("minimal-volume-range-input")
    global.postprocesssettingsResetButton = document.getElementById("postprocesssettings-reset-button")
    global.outputimageCanvas = document.getElementById("outputimage-canvas")
    global.outputfilterControl = document.getElementById("outputfilter-control")
    global.binarizeThresholdInput = document.getElementById("binarize-threshold-input")
    global.binarizeThresholdRangeInput = document.getElementById("binarize-threshold-range-input")
    global.scaleValuesInput = document.getElementById("scale-values-input")
    global.outputfilterResetButton = document.getElementById("outputfilter-reset-button")
    global.sourceimageCanvas = document.getElementById("sourceimage-canvas")
    global.hiddenSourceImage = document.getElementById("hidden-source-image")
    global.hiddenSourceVideo = document.getElementById("hidden-source-video")
    global.sourcefilterControl = document.getElementById("sourcefilter-control")
    global.blurInput = document.getElementById("blur-input")
    global.blurRangeInput = document.getElementById("blur-range-input")
    global.contrastInput = document.getElementById("contrast-input")
    global.contrastRangeInput = document.getElementById("contrast-range-input")
    global.saturateInput = document.getElementById("saturate-input")
    global.saturateRangeInput = document.getElementById("saturate-range-input")
    global.invertInput = document.getElementById("invert-input")
    global.grayscaleInput = document.getElementById("grayscale-input")
    global.sourcefilterResetButton = document.getElementById("sourcefilter-reset-button")
    global.imageselectArea = document.getElementById("imageselect-area")
    global.imageselectInput = document.getElementById("imageselect-input")
    global.captureButton = document.getElementById("capture-button")
    global.resumeButton = document.getElementById("resume-button")
    global.viewAllButton = document.getElementById("view-all-button")
    global.imageSelectButton = document.getElementById("image-select-button")
    global.camImageButton = document.getElementById("cam-image-button")
    global.toggleSourceFilterButton = document.getElementById("toggle-source-filter-button")
    global.outputImageButton = document.getElementById("output-image-button")
    global.toggleOutputFilterButton = document.getElementById("toggle-output-filter-button")
    global.postProcessButton = document.getElementById("post-process-button")
    global.toggleProcessSettingsButton = document.getElementById("toggle-process-settings-button")
    console.log("-> used Elements available in their global variable!")
    return
    
module.exports = indexdomconnect